### ISSUE TITLE
Error with "select load extension"

### ISSUE THREAD

**Issue by mamereu** [dyedgreen/deno-sqlite#100]
The `load_extension(x)` is a [sqlite3 built-in function](https://sqlite.org/lang_corefunc.html), but in deno-sqlite it throws an error:

`const` db = new DB("books.db")
db.query("SELECT load_extension('/opt/sqlite3/sqlite/ext/misc/regexp.so')")
error: Uncaught SqliteError: no such function: load_extension`

Why is that ? In the shell the same select works without problems.

**Comment by dyedgreen** [comment]
The Deno SQLite package runs SQLite in a WebAssemby runtime. This means, we can't load dynamic libraries/ shared objects at runtime (or at least I'm not aware if this is possible, please do correct me if it is).

This means, that the build of SQLite used here removes the `load_extension` build in function.

**Comment by dyedgreen** [comment]
Out of curiosity: Which extension are you trying to load?

**Comment by hobochild** [comment]
I've just run into this too. I was trying to load the `fts5` extension.
