### ISSUE TITLE
Offer API for prepared statements (enables things like more efficient bulk insert)

### ISSUE THREAD

**Issue by jon49** [dyedgreen/deno-sqlite#111]
Would it be possible to have a bulk insert feature?

I looked at the code and it looks like with the `query` method if we pass in an array of objects or array of arrays then we could reuse the statement and get a high performance bulk insert.

**Comment by dyedgreen** [comment]
Hm. I like the idea but I don't think the `query` function would be a good fit for the API (since that would make the types much more complex, and the API harder to reason about).

The key thing that would enable the perf. enhancement you're looking for would be direct access to prepared queries. What do you think of something like this for the API (as a first draft):

```typescript
interface PreparedQuery {
  (Record<string, QueryParam> | QueryParam[]) => Rows;
  finalize: () => void;
}

class DB {
  // ...
  function prepareQuery(sql: string): PreparedQuery { /* ... */ }
}

// then do a bulk insert
let db = new DB("file.db");
let bulkData = [["val1", "val2"], /* ... */];
let query = db.prepareQuery("INSERT INTO data (v1, v2) VALUES (?, ?)");
for (const data of bulkData) {
  query(data);
}
query.finalize();
```

#### Note to self:
This would require a few additional functions in the C part of the library (sqlite docs: https://sqlite.org/c3ref/reset.html)

**Comment by jon49** [comment]
This is how it is done in C#:

https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/bulk-insert

And this is how I'm using it in C#:

https://github.com/jon49/MealPlanner/blob/04683e74299fac59ae632e3c54a61726f7620ce7/ServerApp/MealPlanner.Data/Databases/WriteDataDB.cs#L46
https://github.com/jon49/MealPlanner/blob/04683e74299fac59ae632e3c54a61726f7620ce7/ServerApp/MealPlanner.Core/Database.cs#L163

But I like how you have made it all really simple to interact with the API
very simple and straightforward.

Maybe even a "BulkQuery" call where it handles all the background stuff for
you. I don't know how much lower level API needs to be exposed? Maybe it
would be good, maybe not?

**Comment by dyedgreen** [comment]
I did some thinking around the API and semantics, and came up with this, any thoughts?

# Proposed API
```typescript
interface PreparedQuery {
  (Record<string, BindParam> | BindParam[]) => Rows;
  finalize: () => void;
}

class DB {
  // ...

  // what currently exists
  function query(sql: string, values?: Record<string, BindParam> | BindParam[]): Rows { /* ... */ }

  // proposed 
  function prepareQuery(sql: string): PreparedQuery { /* ... */ }

  // ...
}
```

# Proposed semantics
- `query`: Behaves as it does currently. The rows object is a returning iterator, where the `return` is responsible for cleaning up the statement associated with the query.

- `prepareQuery`: Create a new `PreparedQuery`. The prepared query can be called to effect the database or obtain a `Rows` iterator. However, here the statement is never cleaned up automatically; rather, calling `.finalize()` will clean up the statement.
  - Questions for returned `Rows`: When we make a second query, should that invalidate the previous rows explicitly (i.e. find it and set it's `._done`) 
  - Question for bound parameters: Should we call `sqlite3_clear_bindings`, when the query is run?
  - I think for both, this should be done, as it's not too expensive and makes the API much less easy to misuse.
