### ISSUE TITLE
Idea: Add a top level `cli.ts` which can be used as an SQLite CLI

### ISSUE THREAD

**Issue by dyedgreen** [dyedgreen/deno-sqlite#133]
This might be useful to allow inspecting SQLite databases without having to install anything besides `deno`:

#### Example terminal session:
```
$ deno run --allow-read=. --allow-write=. https://deno.land/x/sqlite/cli.ts my-file.sqlite
SQLite > SELECT * FROM users;
  id       name               email           
 ---- -------------- ------------------------ 
   1   Peter Parker   peter.parker@deno.land  
   2   Clark Kent     clark.kent@deno.land    
SQLite > 
```

I'm not sure how useful this would be though, since I'd imagine most people already have `sqlite3` installed ...

**Comment by dyedgreen** [comment]
While I'm not sure if this is a particularly useful program, it might be a very helpful example :thinking:

**Comment by dyedgreen** [comment]
#138 adds a few examples, including something like this!

**Comment by andykais** [comment]
fwiw, the sqlite program on its own ships with a pretty featureful cli. Up to you if you wish to include this cli in the project, I only caution that you may start to see feature requests creep in for cli specific behavior. E.g.
- "it crashes when I grab 10,000 rows"
- "can we have json highlighting?"
- "can I configure a different table formatting"
etc. Again though, if its cool and/or useful to you, then more power to you!

**Comment by dyedgreen** [comment]
Yes, I agree with that. A cli is pretty useless since almost everyone has a better one installed already. But I believe it makes a decent example 😅
