### ISSUE TITLE
deno.land/x/sqlite version appears out of date

### ISSUE THREAD

**Issue by andykais** [dyedgreen/deno-sqlite#144]
the version on deno.land seems to be very old (https://deno.land/x/sqlite@v2.3.2).
> Version Info
> Nov 19, 2020, 6:26:35 AM

Is there a broken CI pipeline?

**Comment by s-i-e-v-e** [comment]
https://deno.land/x/sqlite should always take you to the latest published version, which is v3.0.0 in this case.

**Comment by dyedgreen** [comment]
If you go to a specific version by adding e.g. `@v2.3.2` to the uri, you will always get that exact version. To get the latest version, just remove the `@vX.X.X`. (I believe there should also be a 'go to latest version' button below the version selector if you're on an older version.)

**Comment by andykais** [comment]
so it does! I goofed with an old link 😅. I didnt notice the "Go to latest" link
