### ISSUE TITLE
Implement File Locking (on `--unstable`)

### ISSUE THREAD

**Issue by dyedgreen** [dyedgreen/deno-sqlite#149]
With https://github.com/denoland/deno/pull/11746 merged, we can add file locking functions to the VFS. This should help with issues like #143.

Initially, this would only work when enabling `--unstable`, but once the APIs are stabilized, this feature can then be enabled by default.

**Comment by NfNitLoop** [comment]
> Initially, this would only work when enabling --unstable

Does that mean that sqlite will no longer work without `--unstable`, or it will use locks only if they're available?

**Comment by dyedgreen** [comment]
@NfNitLoop It will transparently enable locking when on `--unstable`, so it works just the same as now on stable.
