### ISSUE TITLE
Support for getting column names from the result of a select query

### ISSUE THREAD

**Issue by uki00a** [dyedgreen/deno-sqlite#15]
Hi, thanks for the module at first!

I need a way to get column names from the result of a select query.

## Why?

I'd like to convert result rows into an array of object as follows:

```typescript
  const db = new DB();
  db.query("CREATE TABLE test (id INTEGER, name TEXT)");
  db.query("INSERT INTO test (id, name) VALUES (?, ?)", [1, "name"]);
  const rows = db.query("SELECT id as test_id, name as test_name from test");
  const columns = rows.columns(); // This is provisional code.
  assertEquals(columns, ["test_id", "test_name"]);

  const results = [];
  for (const row of rows) {
    const result = {};
    for (let i = 0; i < row.length; i++) {
      result[columns[i]] = row[i];
    }
    results.push(result);
  }
```

Thanks.

**Comment by dyedgreen** [comment]
Hi @uki00a 👋 Thank you so much for the issue and for #16!

Your implementation looks good, but I'm not sure about the API. I'd want to consider a few things before doing a full review and merging your changes:

1. Have you looked at other implementations (the ones I've seen are https://godoc.org/github.com/bvinc/go-sqlite-lite/sqlite3#Stmt.ColumnName and https://www.npmjs.com/package/sqlite3 and they just seem to wrap the C api, which is probably not what we want to do as the package aims to be more high-level and easy to use)
2. I'd like to consider a few alternatives, the ones I can think of right now would be:
   - Have a `columns` function which returns the names (as in your implementation)
   - Provide a `asObject` (or similarly named) function on `Rows` which returns an iterator over `{columnName: value}` objects
   - Provide an option object to `Db.query` which allows to specify how to return rows (as arrays or as objects)
   - (if you have other ideas, definetly add them to this list, so we can discuss them)
3. I'm curios what your use-case is exactly, and whyt other use-cases you can think of. Which API would make these the most easy, which API would have the smallest overead implementation/ performance wise. And which one would give the best ergonomics for the use-cases you have?

We might just end up with the API you suggested, but I want to make sure to get the API right 😃 

And again many thanks for the issue and PR, I really apprechiate the time you took to write the implementation!

**Comment by hsjoberg** [comment]
I think iterating in the form of `{ column1: value, column2: value .... }` for each row makes a lot of sense. Not exactly the same use case you gave, but if you want to get all fields in its own array you could run `Object.keys()` on that object.

**Comment by dyedgreen** [comment]
Some thoughts about the API alternatives I proposed yesterday:

## Object / KeyValue iterator
I feel like for most uses, this interface is no big improvement, specifically consider the following examples:
```javascript
// Current
for (const [a, b, c] of db.query("...")) {
  const obj = { a, b, c };
  // use obj
}
const objects = [...db.query("...")].map(([a, b, c]) => { a, b, c });

// Proposed
for (const obj of db.query("...").keyValues()) {
  // use obj
}
const objects = [...db.query("...").keyValues()];
```

I'd argue that the current way provides more flexibility and is more easily readable, as users directly control how the object is constructed.

Especially since getting the column names is probably a rather unusual requirement (i.e. only really makes sense if the SQL query is user supplied and to be introspected in some way). I'd venture a guess that in this case the user probably also wants more control than just having an iterator of key-value objects.

Another use-case however would be rather awkward: consider you want to know the column names, and all values as an array, then you'd need to do something like this:
```javascript
// Proposed
const names = [];
const rows = [];
for (const obj of db.query("...").keyValues()) {
  if (!names.length)
    names.push(...Object.keys(obj));
  for (const key of names)
    rows.push(obj[key]);
}
```

This feels rather awkward and has a lot of unnecessary indirection.

## `columns()` function (original proposal)
Especially the second example will go much smoother in this case:
```javascript
// Proposed
const rows = db.query("...");
const names = rows.columns();
const values = [...rows];
```

This is probably the more usual use-case (as creating objects arrays/ iterators is trivial, if you control the SQL string and don't need to reflect the `AS name` in there through introspection, which (added bonus) should also be more performant).

Another consideration is the following: Sqlite provides further introspection (see https://sqlite.org/c3ref/column_database_name.html). Uses interested in the column name, might also be interested in these. (again @uki00a if you could elaborate your exact use, case this might further aide the discussion 😊)

## Proposed interface
I would propose an interface similar to what we have currently in #16:

- `Rows` class has a `columns()` function
- The function returns an array of objects with the following keys:
```javascript
{
  name: "sqlite3_column_name",
  originName: "sqlite3_column_origin_name",
  tableName: "sqlite3_column_table_name",
}
```

(Note that the `sqlite3_column_database_name` is omitted on purpose, see #18)

I think that an interface like that will be most useful to people who need to introspect queries in this way.

**Comment by uki00a** [comment]
@dyedgreen @hsjoberg Sorry for the late reply and thanks for the suggestions.

> 3. I'm curios what your use-case is exactly, and what other use-cases you can think of.

What I really want is to get an each row as an object.

So I personally prefer `Rows#asObject` or `Rows#keyValues`.

**Comment by dyedgreen** [comment]
> What I really want is **to get each row as an object and iterate it** as follows:
> 
> ```js
> for (const row of rows.keyValues()) { // or rows.asObject()
>   doSomethingWithRow(row);
> }
> ```

Is there a specific reason why you can't use something like the following in your case? I'm trying to understand, if iterating objects is covered well enough by the current API.
```javascript
for (const [a, b, c] of db.query("...")) {
  doSomethingWithRow({ a, b, c });
}
```

**Comment by uki00a** [comment]
> Is there a specific reason why you can't use something like the following in your case @uki00a?

I'm currently trying to make an ORM library.

To do this, I need to execute queries that are created dynamically by users.

In that case, if there is no means to iterate each row as an object, I must extract columns as follows:

```javascript
const rows = db.query(queryThatIsCreatedDynamicallyAndIDoesNotKnowTheDetails);
const match = /someComplexRegExp/.exec(queryThatIsCreatedDynamicallyAndIDoesNotKnowTheDetails);
const columns = extractColumnsFromMatch(match);
for (const row of rows) {
  const object = {};
  for (const i = 0; i < columns.length; i++) {
    object[columns[i]] = row[i];
  }
}
```

**Comment by dyedgreen** [comment]
I see. That makes sense. I think your suggested API still makes the most sense for the following reasons:

1. It allows to expose the origin names (column table) in an idiomatic way alongside the given names
2. It gives more flexibility to users like you who need the introspection (eg you might want to use a combination of table name, column name in your keys, which would not be easy to implement using the object iterator.)
3. Given the array of names, creating the objects is straight forward. Further for most users creating objects is already trivial given the current api
4. It is easier to implement and maintain within the library e.g. it prevents from potentially having two iterators that try to read from the same query, which may cause issues.

Let me know what you think @uki00a (and @hsjoberg if you want to weight in 😁) Once we agree on a good direction for the API, we can get started reviewing your PR 😊

**Comment by uki00a** [comment]
@dyedgreen 

> 3. Given the array of names, creating the objects is straight forward.

I agree with it. With the array of column names, I can easily do what I want.

> 4. It is easier to implement and maintain within the library

I think good API is:

- simple (so, easy to maintain)
- difficult to use it incorrectly
- to do one thing well

>  e.g. it prevents from potentially having two iterators that try to read from the same query, which may cause issues.

So I think the above is very important.

With those in mind, I think the API that I proposed first (`Rows#columns`) would be good.

**Comment by hsjoberg** [comment]
I would disagree, I think it's fairly conventional to provide "key-value"-based row instead of index-based. Especially for larger queries it's very easy to make mistakes if you require each field to be provided in specific array indices.

It's common to be able to access fields in a key-value object by their field name:
```Javascript
const result = db.query("SELECT field1, field2, field3 FROM tbl");
for (const row of result.rows()) {
   doSomething(row.field1, row.field2, row.field3);
}
```

I strongly agree with keeping the lib simple though, but I think that this functionality is essential.  
Perhaps it's possible o find a middle-ground, I don't know the internals of SQLite enough to give an educated answer to this, but if we go with @uki00a's proposal, I think we should have a helper function that automatically fixes the object for you.

**Comment by dyedgreen** [comment]
> I would disagree, I think it's fairly conventional to provide "key-value"-based row instead of index-based. Especially for larger queries it's very easy to make mistakes if you require each field to be provided in specific array indices.

@hsjoberg I don't think there are many cases where this requires introspection though, can you think of common cases where the following pattern would not work:
```javascript
for (const [someName, someOtherName, ..., someLastName] of db.query("...")) {
  // use the variables
  // or use an object
  const obj = {someName, someOtherName, ..., someLastName};
}
```

My point is, that I feel the use-case for this type of introspection is typically more advanced (building a query-analysis tool/ a SQL Gui/ a ORM/ ...). In these cases consumers typically want more control and are okay with constructing the objects manually from the column name array.

Some of these use-cases also would not be covered by an iterator at all (see above comment).

**Comment by hsjoberg** [comment]
@dyedgreen It would work to make it to an object as  in the example provided, but I would say that this is very error prone, thus I would strongly advice against it. As the queries get larger, the risk for errors increases a lot as you need to provide them in the right order. Also, albeit it could be considered bad practice, `SELECT * ...` would be even more difficult to maintain.

If you look at different database libraries available for Node, i.e [`mysql`](https://www.npmjs.com/package/mysql), [`sqlite3`](https://www.npmjs.com/package/sqlite3), [`postgres`](https://www.npmjs.com/package/postgres), [`oracledb`](https://github.com/oracle/node-oracledb/blob/master/examples/example.js#L120), they all provide object based rows out of the box.

(Sorry if I sound rude in this message, this is not intended.)

Cheers :blush: 
Hampus

**Comment by dyedgreen** [comment]
> (Sorry if I sound rude in this message, this is not intended.)

No worries, you're not rude at all! I'll have a look at the APIs you provided, they should be quite good in terms of guidance on this problem.

> is very error prone

I suppose that's true, although providing the object iterator just shifts the error prone behaviour to defining the `column AS name` in the SQL. (As SQLite does not guarantee what the column name is unless specified with `AS`, so if you wanted to have e.g. the column-names of the origin table in your `SELECT * FROM ...` query, you'd need to use the origin name).

Subtleties like this are the reason I'd personally discourage this type of introspection, unless you have a very specific need for it. (In which case I feel having the array with the `{name, originName, tableName}` data provides the most flexibility).

This being said I'll still want to have a look at the prior art before making a decision on this and moving forward with the PR 😄

**Comment by uki00a** [comment]
FYI:

- Node's [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) module provides a way to switch between index-based and key-value-based approach (`Statement#raw`)
  - https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/api.md#rawtogglestate---this

- Go's [sqlx](https://github.com/jmoiron/sqlx) module provides both index-based (`Rows.SliceScan`) and key-value-based (`Rows.MapScan`) approach.
  - https://godoc.org/github.com/jmoiron/sqlx#Rows
  - https://jmoiron.github.io/sqlx/#altScanning

**Comment by dyedgreen** [comment]
I have to say the `sql` tagged string approach from https://github.com/porsager/postgres is quite interesting 👀 (although I'd personally discourage clever tricks like that, but either is besides the point 😄).

Regarding the API change, and having read the other APIs, I still don't think we should provide a built-in iterator for objects for the following reasons:

1. It's additional complexity (both for uses, as the API grows more complicated and nuanced, and for implementors)
2. The name of the column is not actually that straight forward:
   > The name of a result column is the value of the "AS" clause for that column, if there is an AS clause. If there is no AS clause then the name of the column is unspecified and may change from one release of SQLite to the next.
   I wouldn't want either of the following situations:
   - we upgrade our SQLite version and lot's of users code fails on the new version
   - use `sqlite3_column_origin_name`, confusing uses who used `column AS name`
3. Using objects is significantly slower, as it adds the following overhead:
   - need to retrieve column names for each query
   - need to move names from C -> JS
   - need to construct additional object
   - need to the do hash-lookups for each access
   - (potentially) need to have additional checks to determine iterator mode in use by current rows object
4. And most importantly, given the API we have right now, I don't see a significant improvement in readability/ maintainability of query statements if object iterators are available, compare:

```javascript
// Current
for (const [name1, name2, ..., nameN] of db.query("SELECT a, b, ..., z FROM table")) {
  // do stuff
  // note: the following WILL NOT work:
  name1 = "change data";
}

// Proposed objects iterator
for (const row of db.query("SELECT a AS name1, b AS name2, ..., z AS nameN FROM table")) {
  // do stuff
  // note: the following WILL work:
  row.name1 = "change data";
}
```
(You could achieve the immutability using `{name1} of` in the second example, but that defeats the point and still suffers from all the overhead mentioned.)

One thing that would potentially be simpler with the proposed API change is ignoring returned values (`[,,name,,,]` vs `{ name }` or `obj.name`). But here I would argue that if you need to ignore values, you should not have then returned by the query in the first place.

These considerations, together with the greater flexibility for advanced uses provided by a simple `.columns()` call makes me prefer the `.columns()` API over the object iterators, despite their prevalence in other libraries.

Let me know if you think I missed an important point @uki00a and @hsjoberg. (And apologies for the long discussion, but I feel that it's always easy to add too much functionality and want to make sure that any API provided by `deno-sqlite` is very carefully considered, as deprecating APIs isn't fun for anyone 😅).

@uki00a I'll probably get around to doing a full review tonight (GMT) or tomorrow morning, apologies for blocking your PR for so long. Looking forward to merging your contributions 😊
