### ISSUE TITLE
[feature request] statement typescript types support [column: value] definitions

### ISSUE THREAD

**Issue by andykais** [dyedgreen/deno-sqlite#151]
a follow up to https://github.com/dyedgreen/deno-sqlite/issues/140, for the same reasons that it is useful to query for key value pairs of javascript objects, it would be useful to declare statement rows using key values. Plus defining columns could allow typescript access to be more complete. E.g.
```ts
const rows = db.prepareQuery<{ id: number; name: string }>.all('SELECT id, name FROM person')
rows[0].name // typescript knows this is of type `string`
```

Its possible that statements could support both tuple style and key:value style type definitions via some typescript type inference magic. Is there an interest in this feature?

**Comment by dyedgreen** [comment]
This already works! query/ queryEntries support type parameters for tuples/ records respectively. Prepare supports three optional type parameters for the returned tuple, record, as well as the expected query parameter tuple or record. Is that what you’re looking for? (I believe the deno doc could do a better job of marking type parameters 😅)

**Comment by dyedgreen** [comment]
(See https://github.com/dyedgreen/deno-sqlite/blob/5c57a9ecb8b3fc1cdcc3efcc1ca2feb63cc78616/src/db.ts#L173 for the type script signature)

**Comment by dyedgreen** [comment]
Yes, that's exactly how you'd use it. The tuple and record type are provided separately, to avoid relying on the order of record fields, and to allow more flexible use e.g. with a specific record type, but Array<number> instead of a tuple, etc ...

**Comment by andykais** [comment]
hmm alright. I suppose theres a few cases where its difficult to know for certain if youre dealing with a keyed object vs a tuple without being explicit. Closing this issue as my use case is supported
