### ISSUE TITLE
Password protected DB

### ISSUE THREAD

**Issue by konuch** [dyedgreen/deno-sqlite#154]
Hello, 
does this library support password protection of SQLite DB? I haven’t found anything about it in the docs.
Thanks in advance

**Comment by dyedgreen** [comment]
The built in encryption capabilities of SQLite are a payed extension and as such not available publicly. If you need to use it with Deno, you will need to purchase it from the SQLite developers directly and compile a custom version of the WASM module yourself. See: https://www.sqlite.org/support.html

**Comment by konuch** [comment]
Thanks for clarification. 👍
