### ISSUE TITLE
how to get key/value pairs

### ISSUE THREAD

**Issue by ralyodio** [dyedgreen/deno-sqlite#155]
```
   let user: any = await db.query('SELECT id, email, hashed_password FROM users WHERE email = ?', [body.email]);
    user = user[0];
    console.log(user);
    console.log(body.password, user[2]);
    const comparison = await bcrypt.compare(body.password, user[2]);
    console.log('comparison: ', comparison);

```

seems really weird getting an array of values rather than an array of objects with column names as keys.

Is there a way to get an array of objects?

**Comment by dyedgreen** [comment]
There are methods called `queryEntries`on databases and `iterEntries`, `allEntries`, `oneEntry` on prepared queries, which do exactly what you want 😃
