### ISSUE TITLE
What would it take to make WAL work?

### ISSUE THREAD

**Issue by lusbuab** [dyedgreen/deno-sqlite#158]
In #152 file locking for VFS was introduced. 

I'm wondering what features are still missing to get WAL mode working.

**Comment by dyedgreen** [comment]
To utilize WAL mode, deno would need to support memory mapped files. I’m not sure how feasible that would be.

**Comment by andykais** [comment]
Looks like [absurd-sql](https://github.com/jlongster/absurd-sql) also decided to avoid solving this

> There’s also [write-ahead logging](https://sqlite.org/wal.html), or “WAL mode”. This can be more efficient if working with a real disk. However, to achieve its performance it requires things like shared memory using mmap and things like that. I don’t think we can reliably map those semantics onto IndexedDB, and I don’t even see the point. WAL potentially adds more overhead if we’re just writing them all to IDB anyway. The structure of the writes isn’t as important to us.

**Comment by pikeas** [comment]
WAL mode support is necessary for replicating and backing up SQLite with https://litestream.io/
