### ISSUE TITLE
example for browser

### ISSUE THREAD

**Issue by elycheikhsmail** [dyedgreen/deno-sqlite#167]
I hope to see example using x/sqlite for browser ( may be with react and packup )

**Comment by dyedgreen** [comment]
Running an in-memory database in the browser should work without any extra setup (although you might want to run in a worker).

Running in a browser with an actual file is not currently supported, as this relies on using functions from the `Deno` namespace.

Also see: #105

**Comment by dyedgreen** [comment]
There is now an experimental branch to support easily building a module that works in browsers (persisting the data in indexedDB, and allowing the import and export of databases).

See #168
