### ISSUE TITLE
Bug with insert

### ISSUE THREAD

**Issue by Amatsagu** [dyedgreen/deno-sqlite#170]
Hi, I've run into problem when I wanted to insert new card record like so:
```ts
db.query("INSERT INTO Card (waifuId, ownerId, tier, power, health, stamina, luck, quality) VALUES (?, ?, ?, ?, ?, ?, ?, ?);", [78935, "490068558206992395", 1, 33, 240, 19, 19, 0]);
```

I'm getting error: `no such column: 490068558206992395`. Sometimes I also get: `no such column: %s` (when spamming with it)

That's my Card schema:
```sql
CREATE TABLE "Card" (
	"id"	INTEGER NOT NULL,
	"waifuId"	INTEGER UNSIGNED NOT NULL,
	"ownerId"	VARCHAR(22) NOT NULL,
	"claimerId"	VARCHAR(22),
	"tier"	TINYINT UNSIGNED NOT NULL,
	"power"	SMALLINT UNSIGNED NOT NULL,
	"health"	SMALLINT UNSIGNED NOT NULL,
	"stamina"	SMALLINT UNSIGNED NOT NULL,
	"luck"	TINYINT UNSIGNED NOT NULL,
	"quality"	TINYINT UNSIGNED NOT NULL,
	"locked"	BOOLEAN,
	"tag"	VARCHAR(50),
	PRIMARY KEY("id" AUTOINCREMENT)
);
```

I was able to make this insert by using [DB Browser](https://sqlitebrowser.org/) (gui) so I don't think the command is invalid. I'm using `sqlite@v3.2.0`

**Comment by dyedgreen** [comment]
Do you have a foreign key constraint on that column?

**Comment by Amatsagu** [comment]
Hey, @dyedgreen - I saw you mentioned me earlier *(however it looks like you deleted message)*. My sqlite file don't use foreign keys but I use triggers, is that a problem?

That's how my schema tree looks like.
![image](https://user-images.githubusercontent.com/81469656/149824307-d27acf57-d3fa-4bd5-9a42-5e5209da235a.png)

I tried using my sql file in python app using their std lib for sqlite driver and it was fine. I also made experimental code in TS that spawns a long-living sqlite cli, child process and tried to communicate through it which also worked just fine. Here's tiny speed check of your wasm lib vs. my crappy code that wraps around sqlite cli:
![image](https://user-images.githubusercontent.com/81469656/149824560-2c5611ad-1c3c-4c5d-aea6-ba8123001513.png)

**Comment by Amatsagu** [comment]
Here's my try on brand new db file...
I've generated brand new .db file using deno-sqlite, then added table schemas (worked) and then I tried to make insert:
![image](https://user-images.githubusercontent.com/81469656/149835897-29687139-6427-43b6-ba10-cbae420dcc01.png)

I got error like you can see in console - for proof I did the same through original sqlite cli and it worked without any issues.
*(I tried with `"`, `'` and **`**. I also tried to just write clear text, none of them works)*

**Comment by dyedgreen** [comment]
Hey, yes. Sorry for the confusion, I though it might be related to foreign key constraints, but then realized that that's not actually the problem.

I'm struggling to reproduce the error you're seeing. What happens on your end if you run the following script:
```javascript
import { DB } from "https://deno.land/x/sqlite/mod.ts";

const db = new DB("./new.db");

db.query(`CREATE TABLE IF NOT EXISTS "Card" (
  "id"  INTEGER NOT NULL,
  "waifuId" INTEGER UNSIGNED NOT NULL,
  "ownerId" VARCHAR(22) NOT NULL,
  "claimerId" VARCHAR(22),
  "tier"  TINYINT UNSIGNED NOT NULL,
  "power" SMALLINT UNSIGNED NOT NULL,
  "health"  SMALLINT UNSIGNED NOT NULL,
  "stamina" SMALLINT UNSIGNED NOT NULL,
  "luck"  TINYINT UNSIGNED NOT NULL,
  "quality" TINYINT UNSIGNED NOT NULL,
  "locked"  BOOLEAN,
  "tag" VARCHAR(50),
  PRIMARY KEY("id" AUTOINCREMENT)
);`);

db.query(
  "INSERT INTO Card (waifuId, ownerId, tier, power, health, stamina, luck, quality) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
  [78935, "490068558206992395", 1, 33, 240, 19, 19, 0],
);

console.log(db.query("SELECT *  FROM Card"));
```

**Comment by Amatsagu** [comment]
> Hey, yes. Sorry for the confusion, I though it might be related to foreign key constraints, but then realized that that's not actually the problem.
> 
> I'm struggling to reproduce the error you're seeing. What happens on your end if you run the following script:
> 
> ```js
> import { DB } from "https://deno.land/x/sqlite/mod.ts";
> 
> const db = new DB("./new.db");
> 
> db.query(`CREATE TABLE IF NOT EXISTS "Card" (
>   "id"  INTEGER NOT NULL,
>   "waifuId" INTEGER UNSIGNED NOT NULL,
>   "ownerId" VARCHAR(22) NOT NULL,
>   "claimerId" VARCHAR(22),
>   "tier"  TINYINT UNSIGNED NOT NULL,
>   "power" SMALLINT UNSIGNED NOT NULL,
>   "health"  SMALLINT UNSIGNED NOT NULL,
>   "stamina" SMALLINT UNSIGNED NOT NULL,
>   "luck"  TINYINT UNSIGNED NOT NULL,
>   "quality" TINYINT UNSIGNED NOT NULL,
>   "locked"  BOOLEAN,
>   "tag" VARCHAR(50),
>   PRIMARY KEY("id" AUTOINCREMENT)
> );`);
> 
> db.query(
>   "INSERT INTO Card (waifuId, ownerId, tier, power, health, stamina, luck, quality) VALUES (?, ?, ?, ?, ?, ?, ?, ?);",
>   [78935, "490068558206992395", 1, 33, 240, 19, 19, 0],
> );
> 
> console.log(db.query("SELECT *  FROM Card"));
> ```

I have no clue how but I copy & pasted your test code and this time it worked? What's the difference? I tried earlier with `?` replacing and it was also failing for me...

**Comment by dyedgreen** [comment]
No worries, somethings strange things happen, but I'm happy we could solve your problem 😅

**Comment by Amatsagu** [comment]
> No worries, somethings strange things happen, but I'm happy we could solve your problem 😅

It's not solved yet 😆 
Let me quickly open my main code and update it so we'll see if I can fix current issue. I'm running few micro services that doesn't access db too much but when they do - they need to be able to see the same, sync data so I've made a tiny http server for that:
![image](https://user-images.githubusercontent.com/81469656/149837517-23410dcc-e1ec-46fb-84a1-985d4703c6ca.png)

**Comment by Amatsagu** [comment]
![image](https://user-images.githubusercontent.com/81469656/149838318-d45b7ccd-a192-4bef-94a8-79669231ddc6.png)

It looks legit, I see no errors there but it still throws error. It's basically your code example - just the payload is being received through HTTP/S request.

**Comment by NewtTheWolf** [comment]
with an `in memory database` it works fine

but if you specify a path to a file, unfortunately any `update, create, insert` etc query does not work, is that normal?
