### ISSUE TITLE
Dexecutor seems absent - link is broken

### ISSUE THREAD

**Issue by dsiah** [dyedgreen/deno-sqlite#172]
In the readme there's a link to `dexecutor` project that is broken. https://github.com/denjucks/dexecutor

**Comment by dyedgreen** [comment]
I think we should remove it, if the link is broken? 😅

**Comment by dsiah-aloft** [comment]
haha yes I raised it because my rudimentary searches didn't return anything, but figured project maintainers would know if it had moved or been renamed it 😄

**Comment by dyedgreen** [comment]
Removed the link from the README
