### ISSUE TITLE
Unable to use placeholders in `CREATE TABLE` query

### ISSUE THREAD

**Issue by papiro** [dyedgreen/deno-sqlite#173]
I would expect the following to create a table called "foos":
```
db.query("CREATE TABLE ? (bar, baz)", ["foos"])
```
It throws the error `SqliteError: near "?": syntax error`. 

Ultimately I would like to also use placeholders for the column names. Is this not possible?

**Comment by dyedgreen** [comment]
SQLite unfortunately does not allow for placeholders as table names.
