### ISSUE TITLE
how do i fix this error?

### ISSUE THREAD

**Issue by ralyodio** [dyedgreen/deno-sqlite#177]
`TS2344 [ERROR]: Type 'string' does not satisfy the constraint 'unknown[]'.
      const query = db.prepareQuery<string>(`

```  
  const query = db.prepareQuery<string>(
        "SELECT id, email, hashed_password FROM users WHERE email = :email",
      );
```

**Comment by dyedgreen** [comment]
Your type parameter should be something like `[number, string, string]`
