### ISSUE TITLE
Which SQLite extensions are built into the WASM version?

### ISSUE THREAD

**Issue by shah** [dyedgreen/deno-sqlite#183]
This is a great library, thanks for putting it together. Is there a place I can look to see which extensions are compiled into the WASM version of SQLite that the library exposes?

**Comment by dyedgreen** [comment]
Currently it’s only json support. But the up-to-date list can be found [here](https://github.com/dyedgreen/deno-sqlite/blob/a1dd676335a7ea27a7afafff8e041238d16abdda/build/Makefile#L58).
