### ISSUE TITLE
Insert Query doesnt run

### ISSUE THREAD

**Issue by NewtTheWolf** [dyedgreen/deno-sqlite#190]
Well, all I know is that it runs through queries that select something quickly, but insert queries (I suspect they are not the only ones) just don't run through, the log just stops and nothing happens.

```
deno 1.20.6 (release, x86_64-pc-windows-msvc)
v8 10.0.139.6
typescript 4.6.2
```

Code:

```ts
const db = new DB("database.db", { mode: "write" });

console.log("[DATABASE]", "Inserting users...");

console.log(db.query("SELECT username FROM user"));

db.query("INSERT INTO `user` (`username`) VALUES ('Peter Parker')");

console.log("[DATABASE]", "Finished users...");
```

Screenshots:
![image](https://user-images.githubusercontent.com/59208097/163631522-e065a5e2-6352-4604-bb38-72df5579e6fd.png)

**Comment by dyedgreen** [comment]
Closing this in favor of #191
