### ISSUE TITLE
[deno-deploy] Deno.openSync is not a function

### ISSUE THREAD

**Issue by ynwd** [dyedgreen/deno-sqlite#196]
I just ran this code on Deno deploy.

```ts
const file = Deno.openSync("/foo/bar.txt", { read: true, write: true });
// Do work with file
Deno.close(file.rid);
```

https://dash.deno.com/playground/heavy-mouse-20

And got an error:

```
TypeError: Deno.openSync is not a function
    at file:///src/main.ts:1:19
```

**Comment by dyedgreen** [comment]
That’s a limitation in the deno deploy platform, so there isn’t much we can do about it here 😔

**Comment by sigmaSd** [comment]
Hello I'm successfully using deno sqlite in deno deploy by leveraging  the in memory db.

In my case the db happens to be in json originally so this works out well!:

```ts
import { DB } from "https://deno.land/x/sqlite@v3.2.1/mod.ts";

export interface StationDBType {
  name: string;
  country: string;
  language: string;
  votes: number;
  url: string;
  favicon: string;
}

export const db = new DB("", { memory: true });
db.query(
  "create TABLE radio_table (name TEXT, country TEXT, language TEXT, votes INT, url TEXT, favicon TEXT)",
);
const jsonDb: StationDBType[] = JSON.parse(
  await Deno.readTextFile("static/db/compressed_db.json"),
);

for (const station of jsonDb) {
  try {
    db.query(
      `insert into radio_table values ('${station.name}', '${station.country}', '${station.language}', ${station.votes}, '${station.url}', '${station.favicon}')`,
    );
  } catch {
    // some rows are broken, ignore
  }
}
```

**Comment by EtienneK** [comment]
Any way around this? I am also using `deno-sqlite `and am also running into this error.

**Comment by EtienneK** [comment]
Also, please consider opening this again. Would make sense for the only sqlite deno library to be used on the main Deno platform.

**Comment by sigmaSd** [comment]
There is also https://github.com/ayame113/mock-file for a in memory db workaround

**Comment by EtienneK** [comment]
I don't use sqlite as an in-memory DB. I use it as a read-only DB with full-text search.

**Comment by sigmaSd** [comment]
Just saying read only and in memory are not contradictory, and full text search works either way.

**Comment by EtienneK** [comment]
Sorry, seems I misunderstood the purpose of mock_file.  Thanks! I should have checked your link before commenting. This is exactly what I needed.

**Comment by sigmaSd** [comment]
Nice good luck these are just the current possible workaounds until deploy platform allows more possibilities
