### ISSUE TITLE
Update after a select query doesn't work

### ISSUE THREAD

**Issue by marcosadriano05** [dyedgreen/deno-sqlite#197]
I create a query to update some data, it's work fine. The query is:
```this.database.query("UPDATE todo SET title = ?, description = ?, start_date = ?, finish_date = ? WHERE id = ?;", [data.getTitle(), data.getDescription(), formatedStartDate, formatedFinishDate, data.getId()])```.

But if i run this query after a select query with the same id, doesn't work. The select query:
```this.database.query("SELECT * FROM todo WHERE id = ?;", [data.getId()]")```.

This problem occur when the data is recent create on database too.

**Comment by dyedgreen** [comment]
Can you provide a minimal script to reproduce the issue?
