### ISSUE TITLE
I have an issue where db is closing before queries are finished

### ISSUE THREAD

**Issue by ralyodio** [dyedgreen/deno-sqlite#198]
Is there any kind of await db.finish() method I can cal before doing db.close()?

I’m doing this in Oak middleware. 

```
//Db
app.use(async (ctx, next) => {
  const db = new DB("database.sqlite");
  const mongo = await client.connect("mongodb://127.0.0.1:27017");
  ctx.state.db = db;
  ctx.state.mongo = mongo;
  await next();
  ctx.state.db.close();
  client.close();
});
```

**Comment by dyedgreen** [comment]
Queries are synchronous, so there is no need to wait for them.

You do need to close any prepared queries you have opened (or you can pass `force = true`)
