### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Amatsagu** [dyedgreen/deno-sqlite#199]
It may be some issue on my side*
I'm using **sqlite@v3.4.0** in app that works for like a really long time. I've started to see slowly increasing memory usage after a few days of constant working.

I've found on internet to maybe close & open db file again to avoid pointers leak but that doesn't seem to fix it. I'm using it in my little experiment how it would be having a tiny database over https since I'm not using it as much and it still takes ~20ms to use even via https.

![image](https://user-images.githubusercontent.com/81469656/176172151-bdd77160-649c-4f0d-97a6-5b0c9f424a4a.png)
*(Ik it's silly idea, as I said - it's just a test)*

Deno starts with like ~16MB usage (following what linux see) and after 40 days, htop see over 90MB usage + 100GB mapped?
![image](https://user-images.githubusercontent.com/81469656/176172407-c11395f9-318a-432b-9437-206be75ba811.png)

I've restarted it and within a week, it again starts to grow:
![image](https://user-images.githubusercontent.com/81469656/176172674-04a497b4-2ea9-4dbd-8a1a-0ae31fc3e7de.png)

**Comment by Amatsagu** [comment]
Idk man, I'm basically green when comes to WASM. I've decided to use wasm version because then I can freely switch betwen windows & linux, x64 & arm CPU without having issues with libs.

Is there an option to add like extra method, let's call it `dbClient#sweep` that could on user request sweep memory in the same way as you say it starts after you reach 4GB? It's quite confusing when you work at application and you have no idea what produces extra memory usage all the time.

When closing database and then opening new one (assigned to the same variable) it seems to drop some of that memory but it's not all. Even after I've setup loop to reopen database every 30min of inactivity - it still grows memory over time.

**Comment by dyedgreen** [comment]
Closing this since I can't replicate the issue locally.

I believe this is most likely an issue elsewhere in your APP, since the SQLite library should not be able to allocate much more than `4GB` (assuming you don't create and hold on to more than one database instance at a time).
