### ISSUE TITLE
Compile XLite support into WASM build?

### ISSUE THREAD

**Issue by shah** [dyedgreen/deno-sqlite#202]
[xlite](https://github.com/x2bool/xlite) SQLite extension to query Excel (.xlsx, .xls, .ods) files as virtual tables would allow me to integrate Excel documents into my `deno-sqlite`-based services. I was curious if that's something on the roadmap or if there are any instructions that I could use to compile it myself?

 `deno-sqlite` is a great library, keep up the great work!

**Comment by dyedgreen** [comment]
I don't think this is in scope for this module.

There are some instructions on how to compile the WASM binary from source here: https://github.com/dyedgreen/deno-sqlite/blob/master/CONTRIBUTING.md#prerequisites

(And a more generic article on how the build setup works here: https://tilman.dev/blog/2019/12/building-webassembly-for-deno)
