### ISSUE TITLE
sample code for iterEntries is wrong

### ISSUE THREAD

**Issue by namityo** [dyedgreen/deno-sqlite#209]
https://github.com/dyedgreen/deno-sqlite/blob/d53755cff98b429be827bc70a83112a5b63094bc/src/query.ts#L388

Is the code below correct?

```ts
for (const { id, name } of query.iterEntries()) { 
```

**Comment by dyedgreen** [comment]
Ah you're right! It should be `iterEntries`, not `iter`! Do you want to open a PR to fix this?
