### ISSUE TITLE
Async API or "Worker mode"?

### ISSUE THREAD

**Issue by zefhemel** [dyedgreen/deno-sqlite#211]
Right now all calls are synchronous, so they're blocking the eventloop. In most applications this is somewhat unacceptable. It would be great if there's a way to run these calls async, or perhaps have a wrapper that wraps it in a Web Worker?

**Comment by dyedgreen** [comment]
If you need the calls to not block the main thread, you can run the database in a worker and post queries / results back and forth (see #205).

**Comment by zefhemel** [comment]
Clear enough 👍
