### ISSUE TITLE
store all executed sql statement (as options)

### ISSUE THREAD

**Issue by elycheikhsmail** [dyedgreen/deno-sqlite#212]
debuging sql always hard, I suggess to add option for saving all sql statement befor execute them in some table(middlwear)
something similar to the following code : 

```
export { DB } from "https://deno.land/x/sqlite/mod.ts"; 
const db = new DB("test.db");
db.options({saveSqlStatementBeforExecute:true}) // defaut false

```
in this way it will be easy to debeug: for example if some params omitted...

**Comment by dyedgreen** [comment]
I don't think something like this belongs into this library. If you need to debug your queries, you can always just log them / store them in user code.

**Comment by elycheikhsmail** [comment]
> I don't think something like this belongs into this library. If you need to debug your queries, you can always just log them / store them in user code.

I don't know how get sql statement prepared by prepareQuery

**Comment by dyedgreen** [comment]
It's just the exact string you pass into `db.prepareQuery`.
