### ISSUE TITLE
why not use finally?

### ISSUE THREAD

**Issue by exe-dealer** [dyedgreen/deno-sqlite#222]
I noticed that you prefer duplicate deallocation logic instead of using finally block. Is there any reason?

https://github.com/dyedgreen/deno-sqlite/blob/4e1758a1b1a3f52f93b1209ec5a4e736fc1d619c/src/wasm.ts#L42
https://github.com/dyedgreen/deno-sqlite/blob/4e1758a1b1a3f52f93b1209ec5a4e736fc1d619c/src/db.ts#L261

**Comment by dyedgreen** [comment]
There is not particularly strong reason 😅
