### ISSUE TITLE
Fails when used as a dependency in a node module

### ISSUE THREAD

**Issue by alexgleason** [dyedgreen/deno-sqlite#230]
I'm using [dnt](https://github.com/denoland/dnt) to convert a deno library which depends on deno-sqlite into an npm module. It fails here:

```
[dnt] Top level await cannot be used when distributing CommonJS/UMD (See deps/deno.land/x/sqlite@v3.7.1/mod.ts 21:1). Please re-organize your code to not use a top level await or only distribute an ES module by setting the 'scriptModule' build option to false.
error: Uncaught (in promise) Error: Build failed due to top level await when creating CommonJS/UMD package.
        throw new Error(
              ^
    at build (https://deno.land/x/dnt@0.34.0/mod.ts:297:15)
    at async file:///home/alex/Projects/strfry-policies/scripts/npm.ts:5:1
```

**Comment by dyedgreen** [comment]
Maybe try this: `only distribute an ES module by setting the 'scriptModule' build option to false`? The top level await is necessary for compiling the required WASM.

If top level await is not an option for you, you can try making your own entry-point [`mod.ts`](https://github.com/dyedgreen/deno-sqlite/blob/87b1da79b461fb79796d534abfa144e2fb2d61a2/mod.ts#L21) where you expose an asynchronous „init“ function or similar. (Something like this is done for the browser distribution.)
