### ISSUE TITLE
Add an api to write the DB to a file

### ISSUE THREAD

**Issue by sigmaSd** [dyedgreen/deno-sqlite#232]
I'm using  deno-sqlite, to open an in memory db that I populate with data, this works really well

But today it happened that I wanted to export this to sqlite file, is it possible to add an api to do that `DB.writeToFile("mydb.sql")` ?

**Comment by dyedgreen** [comment]
You can just get the underlying data using [`DB.serialize`](https://deno.land/x/sqlite@v3.7.2/mod.ts?s=DB&p=prototype.serialize), and then write it using the Deno file system API.

**Comment by sigmaSd** [comment]
thanks @dyedgreen  , one question
```ts
import { DB } from "https://deno.land/x/sqlite@v3.7.2/mod.ts";
const db = new DB(":memory:", { memory: true });
db.serialize("temp") //  Failed to serialize database 'temp'
db.serialize() // works
```
from the docs I thought that if I use the in memory database I have to use `temp` schema but that doesn't seem to be the case, I needed to use the main schema to serialize it
