### ISSUE TITLE
Expose the `#this.#open` property on the DB class instance

### ISSUE THREAD

**Issue by adoublef** [dyedgreen/deno-sqlite#237]
[Here](https://github.com/dyedgreen/deno-sqlite/blob/master/src/db.ts#L140) there seems to be a property that checks if the connection is still open. I would like to know if this can be exposed to the end-user.

My use-case would be due to [this](https://github.com/libsql/libsql-client-ts/issues/67) issue. I wasn't able to get the full API working but I would like to attempt to see if this package could be a viable option.

**Comment by dyedgreen** [comment]
I think adding something along the lines of `isClosed` could make sense. The property is checked my a bunch of the other functions already, and it seems useful generally to know if close has been called.

It’s also extremely simple to implement:
```typescript
get isClosed(): boolean {
  return !this.#open;
}
```

**Comment by dyedgreen** [comment]
If you’re happy to make a PR, I can review and release a new version with this changes 😊

**Comment by adoublef** [comment]
> I think adding something along the lines of `isClosed` could make sense. The property is checked my a bunch of the other functions already, and it seems useful generally to know if close has been called.
> 
> It’s also extremely simple to implement:
> 
> ```ts
> get isClosed(): boolean {
>   return !this.#open;
> }
> ```

Ahh ok yh this makes sense, I can open a PR for that

**Comment by adoublef** [comment]
While I am here, do you know if there is a method that allows the user to run a query retrieving data if there is any? It's apart of the original implementation, though I haven't run into instances where I noticed that. and lastly I am unsure about if there is a `bigint` mode.

Lastly, how do I get around the `error: TypeError: WebAssembly.Instance(): Argument 0 must be a WebAssembly.Module` error when I use a test my forked repo?

**Comment by adoublef** [comment]
yes this seems to have deployed without the ffi issues I was experiencing with the denodrivers' implimplementation.

**Comment by dyedgreen** [comment]
> run a query retrieving data if there is any

Not sure what you mean by that? There is a `query` method on `DB`.

**Comment by dyedgreen** [comment]
> lastly I am unsure about if there is a bigint mode

You can insert `BigInt`s into the database, and if you get back an integer that JS can’t represent as a number it’s returned as a `BigInt`.
