### ISSUE TITLE
Support for binding ArrayBuffers

### ISSUE THREAD

**Issue by fabiospampinato** [dyedgreen/deno-sqlite#247]
Response objects easily give you an ArrayBuffer, but deno-sqlite can only bind a Uint8Array to a blob, and converting an ArrayBuffer to a Uint8Array requires more than 0 lines of code, so I think it would be a nice convenience feature if support for binding ArrayBuffers got added.

**Comment by dyedgreen** [comment]
I'm not quite sure what you mean. The DB will always return a `Uint8Array` from a query that returns a `BLOB` value, and if you want to bind to a SQL variable to an array buffer, you could always just do `new Uint8Array(arrayBuffer)`.

**Comment by fabiospampinato** [comment]
I don't want the DB to give me an arraybuffer, I want me to be able to give the DB an arraybuffer. Something like this:

```ts
const response = await fetch ( '/whatever' );
const arrayBuffer = await response.arrayBuffer ();

db.prepare ( 'some ? query' ).get ( arrayBuffer );
```

Which currently throws because arraybuffers are not bindable.

Can we reopen this?

**Comment by dyedgreen** [comment]
Why could you not just do
```
const response = await fetch( '/whatever' );
const arrayBuffer = await response.arrayBuffer();

db.prepare( 'some ? query').rows([new Uint8Array(arrayBuffer)]);
```

**Comment by fabiospampinato** [comment]
I could, but `arrayBuffer` is way cleaner than `new Uint8Array(arrayBuffer)`
