### ISSUE TITLE
Support dumping and recovering

### ISSUE THREAD

**Issue by fabiospampinato** [dyedgreen/deno-sqlite#248]
SQLite's shell has two pretty cool commands:

- [`.dump`](https://sqlite.org/cli.html#converting_an_entire_database_to_a_text_file): it converts an entire database into a SQL string basically.
- [`.recover`](https://sqlite.org/cli.html#recover_data_from_a_corrupted_database): it's like `.dump` but it for all possible data it can find, including deleted stuff that hasn't been vacuumed yet, and data inside corrupted database.

I don't know if it would be practical to add support for these functions to deno-sqlite, but it sure would be nice, imo.

**Comment by dyedgreen** [comment]
We currently have [serialize](https://deno.land/x/sqlite@v3.8/mod.ts?s=DB#method_serialize_0) and [deserialize](https://deno.land/x/sqlite@v3.8/mod.ts?s=DB#method_deserialize_0). Do these do what you want?

**Comment by fabiospampinato** [comment]
No. Neither of them return me a SQL string. And `serialize` doesn't allow me to extract data from corrupted databases.

**Comment by dyedgreen** [comment]
I don't think those functions exist directly in the [SQLite API](https://sqlite.org/c3ref/funclist.html). I'd be curios to see how the CLI implements those commands; but I'd prefer to only expose things that are possible with the SQL C API directly (transliterated to a more JS friendly API where possible).

**Comment by fabiospampinato** [comment]
Sure, no problem 👍
