### ISSUE TITLE
Assertion in db.test.ts succeeds for the wrong reason

### ISSUE THREAD

**Issue by rherrmann** [dyedgreen/deno-sqlite#256]
I'm wondering if the typo in this SQL statement is intended:
https://github.com/dyedgreen/deno-sqlite/blob/1e98e837c6b2efe1f7b6291501bbe49aca296c9e/src/db.test.ts#L513

Shouldn't the statement fail because of read-only access rather than a syntax error?

**Comment by dyedgreen** [comment]
Yes that seems right. I think we should probably check the specific exception (and fix the syntax error!)
