### ISSUE TITLE
Filtering for NULL doesn't work

### ISSUE THREAD

**Issue by timonson** [dyedgreen/deno-sqlite#35]
The following example returns: `Rows { _db: null, _id: -1, _done: true }`

```typescript
const results3 = (db.query(
  "SELECT Name, Composer FROM tracks WHERE Composer = NULL"
) as unknown) as any[]
```

You can find the sample db here: https://www.sqlitetutorial.net/sqlite-sample-database/

I will add a test for NULL tomorrow if this is desired.

**Comment by dyedgreen** [comment]
Thanks for raising the issue, I’ll have a look at this tomorrow.

The result you get looks a lot like the ‘Empty’ row constant, that you get when there are no rows to iterate over in the result. Maybe the query simply returns no results?

Could you specify the database/ provide a minimal sql snippet that creates the database you run this query against?

**Comment by timonson** [comment]
Hi @dyedgreen, the SQLite db is here: https://cdn.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
It should return a lot of results, otherwise I would not have opened this issue :)

**Comment by dyedgreen** [comment]
Ah, no worries! Thanks for reaching out either way, happy the problem could be resolved quickly! 😄
