### ISSUE TITLE
Add release tags

### ISSUE THREAD

**Issue by halvardssm** [dyedgreen/deno-sqlite#36]
Hi!

Would it be possible to add release tags to this repo? That way I can be sure that nothing breaks when this repo gets updated :)

Thanks!

**Comment by dyedgreen** [comment]
Hi @halvardssm!

Yes, I think that's a good idea, I'll look into it, thank you for the suggestion 😄

**Comment by dyedgreen** [comment]
https://github.com/dyedgreen/deno-sqlite/releases

**Comment by halvardssm** [comment]
Nice! Thanks!
