### ISSUE TITLE
Allow in-memory/temporary databases

### ISSUE THREAD

**Issue by gurch101** [dyedgreen/deno-sqlite#50]
It would be great if this library supported in-memory and temporary databases. I'd like it for testing but I'm sure there are use cases for caching as well.

I tried calling `await open(":memory:")` and `await open("")` hoping this would do the trick but it didn't work.

https://www.sqlite.org/inmemorydb.html

**Comment by dyedgreen** [comment]
To open an in memory database, simply use `new DB()`, currently, the files are completely held in memory until saved, so technically any database in in-memory. However there are considerations for changing that (see #49).
