### ISSUE TITLE
List available ORMs / Higher level APIs

### ISSUE THREAD

**Issue by dyedgreen** [dyedgreen/deno-sqlite#52]
List ORMs and higher level APIs available for use with this library.

**Comment by uki00a** [comment]
As far as I know, the following modules depend on deno-sqlite:

- [deno-nessie](https://github.com/halvardssm/deno-nessie)
- [denolib/typeorm](https://github.com/denolib/typeorm)

**Comment by dyedgreen** [comment]
I've come across the following ones:
- https://github.com/eveningkid/denodb/blob/master/deps.ts
- https://github.com/denjucks/dexecutor/tree/master/clients/libs/sqlite
- (which you already mentioned) https://github.com/halvardssm/deno-nessie/blob/master/deps.ts
