### ISSUE TITLE
Change window.btoa to btoa due to problems with Workers

### ISSUE THREAD

**Issue by xReveres** [dyedgreen/deno-sqlite#69]
Please change window.btoa to btoa located in
https://github.com/dyedgreen/deno-sqlite/blob/master/build/sqlite.js#L7
Because I can not use this module in Worker

**Comment by dyedgreen** [comment]
Thanks for raising the issue! I’ll have a look at fixing this later this week when I find time. (If you need a fix super urgently, feel free to submit a PR, the change should be made in the file ‘build/hack/bundle.js’. The you can use the make file to rerun the bundler)
