### ISSUE TITLE
Docs generator breaks if comment contains /

### ISSUE THREAD

**Issue by hsjoberg** [dyedgreen/deno-sqlite#7]
`generator.js` skips documentation if the comment contains `/`.
Presumably the regex inside `collect` is erroneous:
https://github.com/dyedgreen/deno-sqlite/blob/abe59b8ce6862acf82458fad4e2fef034ec74a94/docs/generate.js#L5

This prevents including URL's in the docs.

Example:
```
/**
 * Test
 * / <- Remove this to make it work
 */

```

**Comment by dyedgreen** [comment]
Closed by 52411d816ff296cace24a93332776a4be1bfd0a4
