### ISSUE TITLE
Closable iterators?

### ISSUE THREAD

**Issue by kfdf** [dyedgreen/deno-sqlite#73]
Closable iterators could be used for resource management? Especially for the `Rows` interface, `Rows.done` is literally what `Rows.return` could have been.
`Rows` and `ColumnName` interfaces are not exported,  which can be an inconvenience unless you use them right away. One common case is when you want to write a helper method that converts rows from tuples to objects.

**Comment by dyedgreen** [comment]
Hey @kfdf, thank you for raising the issue! I haven't heard of Closable Iterators before (at least not as a dedicated TypeScript thing), and couldn't come up with anything from a quick Google search, could you provide some links/ pointers to what you mean in this respect?

Regarding the other point, I agree that these interfaces should probably be exported somewhere 😄

**Comment by kfdf** [comment]
Here is a good explanation.
https://exploringjs.com/es6/ch_iteration.html#sec_closing-iterators

And while slightly unorthodox, that would allow this 
```
let db = new DB('path/to/file.db');
try {
  // use db
} finally {
  db.close();
}
```
to become this
```
for (let db of openDB('path/to/file.db') {
  // use db; can safely throw, return or break
}
```

**Comment by dyedgreen** [comment]
Wow, thanks for flagging this up! I wasn't aware of this feature in the spec, and it would fix a bunch of issues that exist in the current implementation (e.g. throw leaks statements, break leaks statements, etc...)

I'll update the library asap to use this (this should be as simple to replace the `done()` with a `return()` and slightly change it's signature 🤩 )
