### ISSUE TITLE
Insert should return affectedrows and lastidinserted.

### ISSUE THREAD

**Issue by tksilicon** [dyedgreen/deno-sqlite#77]
Insert should return affectedrows and lastidinserted. I am making use of this library in [Dso](https://deno.land/x/dso). Found they were was missing.

**Comment by dyedgreen** [comment]
For the last inserted id see [Db.lastInsertRowId](https://dyedgreen.github.io/deno-sqlite/#/api?id=dblastinsertrowid). Regarding the affected rows, if you need access to that information, we should consider adding a `Db.changes` getter that is backed by https://sqlite.org/c3ref/changes.html, I'll have a look about that one once I have some time this weekend 😄

**Comment by tksilicon** [comment]
Nice, I wish I can contribute. It requires calling changes() function after insert. According to the link above. I looked at this:

 /**
   * DB.lastInsertRowId
   *
   * Get last inserted row id. This corresponds to
   * the SQLite function `sqlite3_last_insert_rowid`.
   * 
   * By default, it will return 0 if there is no row
   * inserted yet.
   */
  get lastInsertRowId(): number {
    return this._wasm.last_insert_rowid();
  }

Where is the _wasm implementation, I can't seem to find it.

**Comment by dyedgreen** [comment]
All the WASM related code is in the ‘build’ folder. You should be a me to essentially copy the way last_insert_rowid is done 😀

**Comment by tksilicon** [comment]
Oh so I can add the code then. Will wait for you.
