### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by hsjoberg** [dyedgreen/deno-sqlite#8]
I'm opening an umbrella ticket for a contribution guide.
These things IMO needs to be resolved for this task to be considered complete:

* [x] Prerequisites; what is needed to build the project (Deno, Emscripten SDK)
* [x] Simple instructions on how to set up Emscripten SDK, I guess linking to their guide should be enough.
* [x] What coding standard is in use.
  * My suggestion is to use Deno's as a foundation: https://deno.land/std/style_guide.md, although simply linking to that page might not be enough
  * For code formatting, perhaps it makes sense to use `deno fmt` to be more aligned with the community
* [ ] General guidelines on how commit and pull requests should be made, i.e atomic commits, whether to use tags (`x: message`) in the commit message.
* [x] How comments of code should be made and look

Source of inspiration could be for example lnd's or Bitcoin Cores's:  
https://github.com/lightningnetwork/lnd/blob/master/docs/code_contribution_guidelines.md  
https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md
Although they are pretty exhaustive.

In general, setting up `deno-sqlite` wasn't difficult at all. My biggest struggle was understanding that I needed the Emscripten SDK and how emscripten works.
Unresolved issues for me is how to properly compile the binary as I cannot get any symbols exported without using `-Wl,--export-all`.

**Comment by dyedgreen** [comment]
@hsjoberg I added a draft in PR #12, let me know what you think

**Comment by dyedgreen** [comment]
@hsjoberg I think the contributing doc draft addresses most of the pain points for new contributors. Regarding use of `deno fmt`, I'd like to defer that to be introduced together with the TypeScript rewrite 😄

Thank you very much for outlining your experience with contributing to the project! (And if you have more ideas for what you'd want included in the contributing doc, PRs and/or issues are always welcome!)

**Comment by hsjoberg** [comment]
@dyedgreen I agree, it looks good! :smiley:

> Regarding use of deno fmt, I'd like to defer that to be introduced together with the TypeScript rewrite

Oh yeah, makes sense.

> Thank you very much for outlining your experience with contributing to the project! (And if you have more ideas for what you'd want included in the contributing doc, PRs and/or issues are always welcome!)

No worries.
I'll think about it. :slightly_smiling_face:

**Comment by hsjoberg** [comment]
Closing this one for now, I would suggest to have some rules for commit messages later on, but probably not needed at this time. The contribution guide that we have today is very useful already.
