### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by tksilicon** [dyedgreen/deno-sqlite#80]
How is transaction implemented? In this [mysql](https://deno.land/x/mysql) connection object is expose to handle transactions. How does it work in this library? This library is being plugged into [DSO](https://deno.land/x/dso).

**Comment by dyedgreen** [comment]
You can use the [standard SQLite way](https://www.sqlite.org/lang_transaction.html) of doing it:
```JS
db.query('begin');
// run some queries ...
db.query('commit');
```

**Comment by dyedgreen** [comment]
(Btw, feel free to reach out if you need any help or encounter any issues while trying to include the library, and let me know once you're done, so I can include DSO in the README 😄  )

**Comment by tksilicon** [comment]
This is an ORM and will be using models to run transactions not SQL. There should be way for the client to implement the begin and commit and expose and then expose a connection that can be passed to the model. We can't have users running SQL when it's an ORM.

**Comment by dyedgreen** [comment]
Yeah, the calls should probably be made in the ORM layer. So your ORM should do the following:
```JS
transaction(async () => { // at this point the ORM should run db.query('begin')
  model.query1(); // run generated SQL ...
  model.query2();
  model.query3();
  return boolValue; // at this point conditionally run db.query(returnedTrue ? 'commit' : 'rollback')
});
```

**Comment by dyedgreen** [comment]
```JS
// example implementation of synchronous transaction:
class Client {
  construct(db) {
    this._db = db;
  }

  transaction(callback) {
    this._db.query('begin');
    try {
      const commit = callback();
      this._db.query(commit ? 'commit' : 'rollback');
    } catch {
      this._db.query('rollback');
    }
  }

  stubQuery() {
    // pretend this runs a query
  }
}

// use it!
const conn = new Client(myDb);

conn.transaction(() => {
  conn.stubQuery();
  return true;
});
```

**Comment by tksilicon** [comment]
> Yeah, the calls should probably be made in the ORM layer. So your ORM should do the following:
> 
> ```js
> transaction(async () => { // at this point the ORM should run db.query('begin')
>   model.query1(); // run generated SQL ...
>   model.query2();
>   model.query3();
>   return boolValue; // at this point conditionally run db.query(returnedTrue ? 'commit' : 'rollback')
> });
> ```

transaction(async () => { // at this point the ORM should run db.query('begin')
  model.insert(); // run generated SQL ...
  model.update();
  model.insert();
  return boolValue; // at this point conditionally run db.query(returnedTrue ? 'commit' : 'rollback')
});

You know the query() is an internal method. So we need to pass the connection into the model to utilize for model internal query() which model exposed methods like insert uses instead of the client. So we can use one connection to mark the transaction boundaries. Probably exposing the connection on the client would do. I don't know if that is possible.

**Comment by dyedgreen** [comment]
I'm afraid I'm not sure how your ORM is implemented exactly. But to run any queries (generated by an ORM or otherwise), you'll need to have the open connection object (i.e. return value from `new DB()`). And if you have that, doing transactions like in my example is fairly straight forward 😃

**Comment by tksilicon** [comment]
> I'm afraid I'm not sure how your ORM is implemented exactly. But to run any queries (generated by an ORM or otherwise), you'll need to have the open connection object (i.e. return value from `new DB()`). And if you have that, doing transactions like in my example is fairly straight forward 😃

Maybe take a look at this [transaction class ](https://github.com/manyuanrong/dso/blob/master/src/transaction.ts) and this [mysql transaction implementation in the client.](https://deno.land/x/mysql@1.5.0/src/client.ts)

**Comment by dyedgreen** [comment]
Yeah, it looks like you'd have access to the client, so you'll have to wrap the SQLite connection in a client specific to your ORM. So you'd write this code in the driver you write for SQLite. I can't seem to find the driver specific code, but once you have the common interface definition, let me know so I can assist you with implementing the driver 😃

**Comment by halvardssm** [comment]
@dyedgreen Would you be open to add a transaction method to the client as you provide with an example here? It would simply be a wrapper, and I think it would remove some confusion for those who are not as familiar with sqlite to run transactions. I can provide a simple merge request if you are ok with it.

> ```ts
>   transaction(callback) {
>     this._db.query('begin');
>     try {
>       const commit = callback();
>       this._db.query(commit ? 'commit' : 'rollback');
>     } catch {
>       this._db.query('rollback');
>     }
>   }
> ```

**Comment by dyedgreen** [comment]
@halvardssm There have been some discussions [here](https://github.com/dyedgreen/deno-sqlite/pull/104) and on the Deno db drivers discord about defining a shared SQL database client interface. I think having a common transaction method on such an interface makes a lot of sense, so I would probably want to hold off with adding something like this to the API until there has been some more discussion in that direction (I'm not opposed to the idea, I think you're right that it will help streamline the interface, but I would like to avoid having to deprecate the transaction method if the design is not in line with a potential shared interface)

**Comment by halvardssm** [comment]
Completely fair, I didn't know about the discussion regarding a common interface, but I am highly supportive of this as it would make the Client wrapper for Nessie a lot easier and simpler. Could you point me in the direction of this discussion as I would like to join in?

**Comment by dyedgreen** [comment]
There have been a few discussions on this discord: https://discord.gg/r5WZ485 😄

**Comment by halvardssm** [comment]
Cool, thanks! I will start a discussion in the discord about creating a new repo for shared interfaces then 👍🏻

**Comment by halvardssm** [comment]
Ah, actually read through the chat log and it seems to already be a conversation going 😅
