### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [dyedgreen/deno-sqlite#83]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by dyedgreen** [comment]
Hi @xcatliu, thanks for the issue!

What's the advantage of Pagic over the current solution docsify?

**Comment by dyedgreen** [comment]
Closing stale issue
