### ISSUE TITLE
Code formatting and coding standards (deno fmt)

### ISSUE THREAD

**Issue by hsjoberg** [dyedgreen/deno-sqlite#9]
Sorry for all the issues/PRs. :slightly_smiling_face: 

Deno seems to take the same approach as Go and Rust, which is to have a conventional code standard and format that projects are suggested to use. I think it makes sense to use `deno fmt` on the whole project to make the code more aligned with the community and other Deno modules.

Related to #8.

**Comment by dyedgreen** [comment]
I think this would be a good idea. This would probably make sense to do as part of #10. The best way to achieve this would probably be as part of the CI for tests (i.e. fail the tests if `deno fmt` touches any files).

**Comment by dyedgreen** [comment]
All code no uses `deno fmt`
