### ISSUE TITLE
Error 22 after file reaches 2GB (WSL2)

### ISSUE THREAD

**Issue by chanibal** [dyedgreen/deno-sqlite#92]
Hi, it looks like the current version of deno-sqlite with current deno does not support files over 2GB.   
Failed at `2147352576` bytes, to be exact (2047.875MB).

Platform: Windows 10 (2004) WSL2 Ubuntu 20.04.1 kernel 4.19.128; both 64 bit

```
error: Uncaught (in promise) TypeError: Invalid argument (os error 22)
    at processResponse (core.js:224:13)
    at Object.jsonOpSync (core.js:248:12)
    at Object.seekSync (deno:cli/rt/30_files.js:13:17)
    at js_write (https://deno.land/x/sqlite@v2.3.1/build/vfs.js:61:12)
    at denoWrite (<anonymous>:0:3953)
    at pager_write_pagelist (<anonymous>:0:34829)
    at sqlite3PagerCommitPhaseOne (<anonymous>:0:26734)
    at sqlite3BtreeCommitPhaseOne (<anonymous>:0:27894)
    at sqlite3VdbeHalt (<anonymous>:0:43134)
    at sqlite3VdbeExec (<anonymous>:0:53409)
```

The code that caused it (after simplification):
```javascript
import { DB } from "https://deno.land/x/sqlite/mod.ts";

const db = new DB("data.db");
db.query("CREATE TABLE IF NOT EXISTS CachedRequest (id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT, status INTEGER, body TEXT, timestamp INTEGER, headers TEXT)");

for(var i = 1; i < 20000; i++) {
  // used for cache, but this is the first run, so nothing is cached
  const rows = [...db.query("select * from CachedRequest where url = ?", [url]).asObjects()];

  // snipped: fetch body, fill row object
  db.query("insert into CachedRequest(body, status, timestamp, headers, url) values(:body, :status, :timestamp, :headers, :url)", row);
}

db.close();
```

I can further grow the database with
```sql
insert into CachedRequest(status,url,body,timestamp,headers) select status,url,body,timestamp,headers from CachedRequest;
```
from the `sqlite3` command line utility, so this is not a WSL limitation. Perhaps something related to WASM?

**Comment by dyedgreen** [comment]
Thank you for reporting the issue @chanibal!

Looking at the output, the issue seems to be located in the js file system wrapper (which talks to the fs through Deno). Might be an issue with overflowing something, I’ll check this out more closely later 😬

**Comment by dyedgreen** [comment]
Just looking into it now I believe the issue you're seeing is caused by overflowing an `i32` int. While there is an absolute limit in terms of `Number.MAX_SAFE_INTEGER`, I think we can still do better than an `i32`'s `2,147,483,647`.

I'll try to make a test-case which generates a large file like this and then see what happens in terms of overflowing 😅
