### ISSUE TITLE
SQLite3 datetime function incorrectly returns UTC as localtime

### ISSUE THREAD

**Issue by Desibabe** [dyedgreen/deno-sqlite#93]
import { DB } from "https://deno.land/x/sqlite/mod.ts";

// Open a database
const db = new DB("test.db");
db.query("CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, date DATE)");

db.query("INSERT INTO people (name, date) VALUES ('Ryan', datetime('now','localtime'))");

// Print out data in table
for (const [name,date] of db.query("SELECT name,date FROM people"))
console.log(name,date);

// Close connection
db.close();

*** Deno Log
Ryan 2020-11-16 01:51:50

*** SQLITE3
SELECT datetime('now', 'localtime');
2020-11-15 19:51:50

*** Version
deno 1.5.2 (71d7482, release, x86_64-pc-windows-msvc)
v8 8.7.220.3
typescript 4.0.5

**Comment by dyedgreen** [comment]
Thank you for opening the issue @Desibabe!

This problem stems from the SQLite module running inside a WebAssembly context with only very limited access to the outside world. So it seems that it sees the localtime as UTC (which should explain the observed difference). I'll have a look if it is possible to expose this information to the Wasm binary 😄
